namespace Calabonga.Catalog.Core
{
    public static partial class AppData
    {
        /// <summary>
        /// Common messages
        /// </summary>
        public static class Messages
        {
            /// <summary>
            /// "User successfully registered"
            /// </summary>
            public static string UserSuccessfullyRegistered => "User successfully registered";

            /// <summary>
            /// "Access Denied"
            /// </summary>
            public static string AccessDenied => "Access Denied";

            /// <summary>
            /// "ViewModel {0} for template generation not registered";
            /// </summary>
            public static string ViewModelForTemplateNotRegistered => "ViewModel {0} for template generation not registered";

            /// <summary>
            /// "Email already registered"
            /// </summary>
            public static string EmailAlreadyRegistered => "Email already registered";

            /// <summary>
            /// "Entity successfully deleted"
            /// </summary>
            public static string EntitySuccessfullyDeleted => "Entity successfully deleted";

            /// <summary>
            /// "Automatically generated by {0}"
            /// </summary>
            public static string ViewModelFactoryGenerationText => "Automatically generated by {0}";

            /// <summary>
            /// "Password reset requested for email {0}. UserId {1}  Code: {2}"
            /// </summary>
            public static string PasswordResetRequested => "Password reset requested for email {0}. UserId {1}  Code: {2}";

            /// <summary>
            /// "Password successfully changed"
            /// </summary>
            public static string PasswordSuccessfullyReset => "Password successfully changed";
            
            /// <summary>
            /// "Budgets not found for hotel"
            /// </summary>
            public static string BudgetNotFound => "Budgets not found for hotel";

            /// <summary>
            /// "No pricepoints found for change status operation"
            /// </summary>
            public static string PricepointsNotFoundForStatusChangeOperation => "No pricepoints found for change status operation";

            /// <summary>
            /// "Find competitors work created"
            /// </summary>
            public static string FindCompetitorWorkCreated => "Find competitors work created";

            /// <summary>
            /// "RoomTypes found for Pricepoint modifications for strategies";
            /// </summary>
            public static string RoomTypesFoundedForStrategyModificator => "RoomTypes found for Pricepoint modifications for strategies";

            #region Exschange

            /// <summary>
            /// "[EXCHANGE]: Pricepoint for exchange operation work successfully created";
            /// </summary>
            public static string PricepointForExchangeWorkCreated => "[EXCHANGE]: Pricepoint for exchange operation work successfully created";

            /// <summary>
            /// "[EXCHANGE]: Pricepoint for exchange operation work successfully updated";
            /// </summary>
            public static string PricepointForExchangeWorkUpdated => "[EXCHANGE]: Pricepoint for exchange operation work successfully updated";

            #endregion

            #region Work

            /// <summary>
            /// "[WORK]: Nothing to do at {0}"
            /// </summary>
            public static string NothingToDo => "[WORK]: Nothing to do at {0}";

            /// <summary>
            /// "[WORK]: Totally founded for processing {0}"
            /// </summary>
            public static string TotalWorkToProcessFound => "[WORK]: Totally founded for processing {0}";

            #endregion
        }
    }
}
